spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name:microservicecloud-config-eilen-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-eilen-test